### ISSUE TITLE
Log rotating fails on Windows when using heka LogstreamerInput

### ISSUE THREAD

**Issue by majj** [mozilla-services/heka#1020]
Config:

[client_log]
type = "LogstreamerInput"
rescan_interval  = "5s"
log_directory = "E:\mabodev\mabo.io\py\heka"
file_match = 'heka_tcp.log.?(?P<Seq>\d*)'
priority = ["^Seq"]
# 

Error :

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\logbook\handlers.py", line 214, in handle
    self.emit(record)
  File "C:\Python27\lib\site-packages\logbook\handlers.py", line 775, in emit
    self.perform_rollover()
  File "C:\Python27\lib\site-packages\logbook\handlers.py", line 767, in perform_rollover
    rename(self._filename, self._filename + '.1')
  File "C:\Python27\lib\site-packages\logbook\helpers.py", line 159, in rename
    os.rename(src, dst)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

Is there something  wrong in my configuration?

**Comment by justenwalker** [comment]
Seems like this is still a problem on the latest `dev` branch. Any chance of this being fixed?

I think there is an underlying limitation in Golang that it does not pass FILE_SHARE_DELETE access mode... This make any log rolling method fail to rename files being watched by Heka logstreamer.

See:
- [CR 8203043](https://codereview.appspot.com/8203043/)
- [SO Question](http://stackoverflow.com/questions/23897174/is-it-possible-to-open-a-file-allowing-another-processes-to-delete-this-file)

FWIW - elastic beats has this: https://github.com/elastic/beats/blob/master/filebeat/input/file_windows.go

**Comment by justenwalker** [comment]
I was able to use `github.com/elastic/beats` to overcome this issue. 

https://github.com/justenwalker/heka/commit/7eb06d8bd698c3a51d784cb127ffc4718c8114b3
