### ISSUE TITLE
preserve_data = true not really as advertized

### ISSUE THREAD

**Issue by wyndhblb** [mozilla-services/heka#1252]
It seems that heka "wipes out" the CBuf data on restarts and plugin "stops" (sandbox_encoder.go Line 151) even with  preserve_data = true.  I'm not sure if that is on purpose or if it is a flaw, but otherwise i'm not sure why there is a preserve_data flag.

**Comment by wyndhblb** [comment]
```

[logger-syslog-decoder]
type = "PayloadRegexDecoder"
match_regex = '^(<\d+>)?(?P<Timestamp>[A-Z][a-z]+\s+\d+\s\d+:\d+:\d+) (?P<Hostname>\S+) (?P<Logger>\S+): (?P<log_message>.*)'
timestamp_layout = 'Oct 23 00:34:49'
timestamp_location = 'UTC'

    [logger-syslog-decoder.severity_map]
    DEBUG = 7
    INFO = 6
    WARNING = 4
    WARN = 4
    ERROR = 3
    CRITICAL = 2
    FATAL = 2

    [logger-syslog-decoder.message_fields]
    Type = "mylogger-service"
    Hostname = "%Hostname%"
    Logger = "%Logger%"
    log_message = "%log_message%"

[logger-stats-acum]
type = "StatAccumInput"
ticker_interval = 10
delete_idle_stats = true
message_type = "mylogger-service.stats"

[logger-stats]
type = "StatFilter"
stat_accum_name = "mylogger-stats-acum"
message_matcher = "Type == 'mylogger-service'"

    [logger-stats.Metric.messagecount]
    type = "Counter"
    name = "loggerstat.%Hostname%"
    value = "1"

    [logger-stats.Metric.all-count]
    type = "Counter"
    name = "loggerstat.all"
    value = "1"

[logger-stats-graph10]
type = "SandboxFilter"
filename = "lua_filters/stat_graph.lua"
ticker_interval = 10
preserve_data = true
message_matcher = "Type == 'mylogger-service.stats'"

  [logger-stats-graph10.config]
  title = "Total Messages 10sec"
  rows = 1440
  stat_aggregation = "none"
  stat_unit = "count"
  sec_per_row = 10
  stats = "stats.counters.loggerstat.all.count"
  stat_labels = "Messages"
```

It turns out that the `logger-stats-graph10` is empty (for reasons i'm still trying to figure out).  however It seems that when the 1440 row count is "up" any other CBUFs get "wiped / nulled out" from `dashboard/data/` directory ONLY if i include the `logger-stats-graph10` cbuf in the config.

This is running the current 0.8.1 version of things

**Comment by wyndhblb** [comment]
And there's more ... i noticed today (this may be a different bug, but related to preserve failing) when for some reason my AWS's elastic search nodes did not respond. The elasticsearch cluster is/was just fine, but it being AWS god knows what happens to networks sometimes, but the ES did get back to responding within a few seconds. Heka never recovered...  just repeated this over and over for hours, until i noticed it borked .. 

```
2015/01/04 00:00:54 Plugin 'logger-es-output' error: HTTP request failed: Post http://service-elasticsearch-log-prod.mfpaws.com:9200/_bulk: EOF
2015/01/04 00:01:45 Plugin 'logger-es-output' error: HTTP response error status: 504 Gateway Time-out
2015/01/04 00:02:35 Plugin 'logger-es-output' error: HTTP response error status: 504 Gateway Time-out
2015/01/04 00:03:24 Diagnostics: 2 packs have been idle more than 120 seconds.
2015/01/04 00:03:24 Diagnostics: (inject) Plugin names and quantities found on idle packs:
2015/01/04 00:03:24 Diagnostics:        dashboard: 2
2015/01/04 00:03:24
2015/01/04 00:03:24 Diagnostics: 98 packs have been idle more than 120 seconds.
2015/01/04 00:03:24 Diagnostics: (input) Plugin names and quantities found on idle packs:
2015/01/04 00:03:24 Diagnostics:        log-level-info-60sec: 98
015/01/04 00:05:24 Diagnostics: 98 packs have been idle more than 120 seconds.
2015/01/04 00:05:24 Diagnostics: (input) Plugin names and quantities found on idle packs:
2015/01/04 00:05:24 Diagnostics:        log-level-info-600sec: 98
2015/01/04 00:10:54 Diagnostics: 98 packs have been idle more than 120 seconds.
2015/01/04 00:10:54 Diagnostics: (input) Plugin names and quantities found on idle packs:
2015/01/04 00:10:54 Diagnostics:        log-level-info-60sec: 98
....

015/01/04 02:50:24 Diagnostics: 98 packs have been idle more than 120 seconds.
2015/01/04 02:50:24 Diagnostics: (input) Plugin names and quantities found on idle packs:
2015/01/04 02:50:24 Diagnostics:        log-level-info-60sec: 98
2015/01/04 02:50:24
2015/01/04 02:50:53 Shutdown initiated.
2015/01/04 02:50:53 Stop message sent to input 'mfp-service-logger-tcp'
2015/01/04 02:50:53 Stop message sent to input 'mfp-service-logger-udp'
2015/01/04 02:50:53 Stop message sent to input 'mfp-service-logger-stats-acum'
2015/01/04 02:50:53 Input 'mfp-service-logger-udp': stopped
panic: runtime error: send on closed channel

goroutine 37 [running]:
runtime.panic(0x9c21e0, 0xf5579e)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/mozilla-services/heka/pipeline.(*StatAccumInput).DropStat(0xc2080058c0, 0xc20a9b2660, 0x2f, 0xc20a1df488, 0x1, 0xa38530, 0x0, 0x3f800000, 0x0)
        /opt/heka/src/build/heka/src/github.com/mozilla-services/heka/pipeline/stat_accum_input.go:188 +0x93
github.com/mozilla-services/heka/plugins/statsd.(*StatFilter).Run(0xc208132840, 0x7f629a7e9350, 0xc208059e00, 0x7f629a7e9df0, 0xc20803e140, 0x0, 0x0)
        /opt/heka/src/build/heka/src/github.com/mozilla-services/heka/plugins/statsd/stat_filter.go:121 +0x7d3
github.com/mozilla-services/heka/pipeline.(*foRunner).getWrapperAndRun(0xc208059e00, 0xc20812a160, 0xc20812eab0, 0x0, 0x0)
        /opt/heka/src/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:523 +0x14e
github.com/mozilla-services/heka/pipeline.(*foRunner).Starter(0xc208059e00, 0x7f629a7e9df0, 0xc20803e140, 0xc20803e1c0)
        /opt/heka/src/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:636 +0x1d9
created by github.com/mozilla-services/heka/pipeline.(*foRunner).Start
        /opt/heka/src/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:496 +0x96
        
goroutine 16 [semacquire]:
sync.runtime_Semacquire(0xc216611310)
        /usr/local/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc20803e240)
        /usr/local/go/src/pkg/sync/waitgroup.go:129 +0x14b
github.com/mozilla-services/heka/pipeline.Run(0xc20803e140)
        /opt/heka/src/build/heka/src/github.com/mozilla-services/heka/pipeline/pipeline_runner.go:287 +0x190e
main.main()
        /opt/heka/src/build/heka/src/github.com/mozilla-services/heka/cmd/hekad/main.go:188 +0xf64
        
...LOT MORE of that kind of stuff....

````
then i restarted the hekad process ... and my preserved data was "gone" ..

**Comment by trink** [comment]
If Heka crashes like above (or is killed) the sandbox state will not be preserved since it runs on shutdown.  As far as the buffer getting zero'ed out; I would take a good look at your input data; if the timestamps are before the start of the buffer the additions will be ignored and if they are far ahead of the buffer it will advance dropping all the old data.  If the data look good please check the permissions on your sandbox_preservation directory and see if there is anything being written to it on a clean shutdown.
