### ISSUE TITLE
Investigate DashboardOutput memory leak

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/heka#1422]
We have reports of DashboardOutput leaking memory over the course of a long-running Heka process, see https://mail.mozilla.org/pipermail/heka/2015-March/000384.html.

**Comment by intjonathan** [comment]
We see similar patterns though we haven't gone to the work of identifying it as DashboardOutput. We had to put cgroup limits on our aggregation instances, which helped but is a bandaid. End up with restarts at these peaks.
![memory_-_new_relic](https://cloud.githubusercontent.com/assets/518164/6699056/97d1b8a6-ccbb-11e4-9e6d-8117ea79b8cd.png)

**Comment by rafrombrc** [comment]
@intjonathan I've been trying to reproduce this locally and haven't been able to. I'm wondering if you might be able to help debug? What would be awesome is if you could add a `memprof = "/path/to/mem.prof"` setting to the `[hekad]` section of your config so we can capture a memory allocation profile. Then, when the memory usage grows, stop hekad, move the profile out of the way so it doesn't get overwritten when you restart. It's important to capture when the usage is high so we the leaky allocations will be more likely show up in the profile.

No worries if this isn't possible, but if it is the data would be very helpful. Thanks!

**Comment by intjonathan** [comment]
Unfortunately I haven't been able to capture the memprof for you, instead I attacked this from a couple angles: upgrading to 0.9.2, and rewriting an accumulating filter -> http message flow into a native Lua output. It seems to have alleviated the oom killer restarts. Sorry that doesn't help you move forward on the issue at hand here. :/

**Comment by rafrombrc** [comment]
I'm pretty sure that the DashboardOutput related leaks would only happen when the router is backed up... the DashboardOutput spins up a goroutine to generate the report messages every ticker_interval. When the router is backed up, or when there are no packs available in the injectRecycleChan, then these goroutines will be stuck and never exit. If this state continues, goroutines will accumulate and slowly drain system resources.

**Comment by mattupstate** [comment]
@rafrombrc I've experienced this memory issue as well. I'm curious what would cause the router to get "backed up"?

**Comment by rafrombrc** [comment]
@mattupstate Have you concretely linked it to the DashboardOutput? If so, I'd love to work with you to try to debug the issue.

There are many things that might cause the router to back up, but in general the answer is that one or more of the plugins attached to the router (i.e. filter or output plugins) is either processing messages so slowly that its input channels back up to the router, or it's not recycling messages when it's finished with them, so that the messages are never freed up to be reused.

In this particular case the original thread (linked in my opening comment on this issue) was referring to a situation where Heka was freezing and the DashboardOutput was concretely linked to a memory leak. Since I've been unable to reproduce a DashboardOutput memory link under normal conditions, and it's very clear to me how such a leak would happen if Heka was wedged, my current hypothesis is that the original user's leak was a secondary symptom of the wedging.

This is still just a hypothesis, though, any additional information that can be gathered would be helpful.

**Comment by mattupstate** [comment]
No, haven't nailed it down. We just recently noticed that a long running hekad instance was consuming as much as 2GB of memory at times. The best I can provide is the config at the time and some log output.

```
goroutine 241684 [chan receive]:
github.com/mozilla-services/heka/pipeline.(*PipelineConfig).allReportsData(0xc20804ca00, 0x0, 0x0, 0x0, 0x0)
	/home/admin/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/report.go:198 +0x176
github.com/mozilla-services/heka/pipeline.(*PipelineConfig).AllReportsMsg(0xc20804ca00)
	/home/admin/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/report.go:238 +0x27
created by github.com/mozilla-services/heka/plugins/dasher.(*DashboardOutput).Run
	/home/admin/heka/build/heka/src/github.com/mozilla-services/heka/plugins/dasher/dashboard_output.go:292 +0x1a91

goroutine 241704 [chan receive]:
github.com/mozilla-services/heka/pipeline.(*PipelineConfig).reports(0xc20804ca00, 0xc226e38e40)
	/home/admin/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/report.go:81 +0xa3
created by github.com/mozilla-services/heka/pipeline.(*PipelineConfig).allReportsData
	/home/admin/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/report.go:194 +0xf2
```

```
[hekad]
maxprocs = 2

[dashboard]
type = "DashboardOutput"
ticker_interval = 1

[app_nginx_access_log_input]
type = "LogstreamerInput"
log_directory = "/opt/app/log"
file_match = 'nginx\.access\.log'
decoder = "api_nginx_access_log_decoder"

[app_nginx_access_log_decoder]
type = "SandboxDecoder"
filename = "lua_decoders/nginx_access.lua"

    [app_nginx_access_log_decoder.config]
    type = "nginx.access"
    user_agent_transform = true
    user_agent_conditional = true
    log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $request_time $upstream_response_time "$http_referer" "$http_user_agent"'

[app_nginx_nginx_status]
type = "SandboxFilter"
filename = "lua_filters/http_status.lua"
ticker_interval = 1
preserve_data = true
message_matcher = "Type == 'nginx.access'"

        [app_nginx_nginx_status.config]
        sec_per_row = 1
        rows = 1800
        perservation_version = 0

[app_nginx_error_log_input]
type = "LogstreamerInput"
log_directory = "/opt/app/log"
file_match = 'nginx\.error\.log'
decoder = "api_nginx_error_log_decoder"

[app_nginx_error_log_decoder]
type = "SandboxDecoder"
filename = "lua_decoders/nginx_error.lua"
```

**Comment by rafrombrc** [comment]
In the "Heka is wedged" case I was describing above, there would be hundreds or possibly thousands of active goroutines, all hung up in the `report.go` code like the two goroutines you pasted above. If you send a SIGQUIT signal to the `hekad` process while it's in the high-memory use state you described you'd see this, in case that helps with the debugging process.

**Comment by erichandsmith** [comment]
We are seeing the same issue. I enabled memory profiling with and without DashBoardOutput. The results can be found here: https://gist.github.com/erichandsmith/8a66441e929438912893

**Comment by robison** [comment]
I've been seeing some fairly large memory utilization on a pair of hosts that I'm using as Heka message routers; at first, I thought that the issue might be related to the DashboardOutput. After disabling it, I'm still seeing the same thing on both hosts - ~250MB/hour increase in memory use, at about ~3000 msgs/sec per host. Turned on memory profiling on one of them, will include some results here later today.
