### ISSUE TITLE
Splitter crashes if delimiter is not found

### ISSUE THREAD

**Issue by k2xl** [mozilla-services/heka#1453]
Splitter seems to crash when delimiter is not present. For example, if delimiter is \n and there is only one message from the input, unless there is a trailing \n things seem to break.

Here is stack track (from using AMQP input):
``` 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4f2f57]

goroutine 69 [running]:
github.com/mozilla-services/heka/plugins/amqp.(*AMQPInput).Run(0xc208112300, 0x7f49533377b0, 0xc2080fc7e0, 0x7f495333b498, 0xc20803a820, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/amqp/amqp_input.go:194 +0x377
github.com/mozilla-services/heka/pipeline.(*iRunner).Starter(0xc2080fc7e0, 0x7f495333b498, 0xc20803a820, 0xc20803a960)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:283 +0x180
created by github.com/mozilla-services/heka/pipeline.(*iRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:266 +0x606

goroutine 1 [chan receive]:
github.com/mozilla-services/heka/pipeline.Run(0xc20803a820)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/pipeline_runner.go:271 +0x143c
main.main()
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/cmd/hekad/main.go:191 +0x12a6

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc208014b50, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208014b50, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208014af0, 0xc208073000, 0x1000, 0x1000, 0x0, 0x7f4953333d30, 0xc20802f258)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208030070, 0xc208073000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc2080507e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc2080507e0, 0xc20802f250, 0x7, 0x7, 0xc200000001, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f4953338d30, 0xc2080507e0, 0xc20802f250, 0x7, 0x7, 0x7, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f4953338d30, 0xc2080507e0, 0xc20802f250, 0x7, 0x7, 0xc208057680, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/streadway/amqp.(*reader).ReadFrame(0xc20809ab90, 0x0, 0x0, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/streadway/amqp/read.go:48 +0xcd
github.com/streadway/amqp.(*Connection).reader(0xc208052140, 0x7f4953338c98, 0xc208030070)
	/home/ec2-user/heka/build/heka/src/github.com/streadway/amqp/connection.go:455 +0x110
created by github.com/streadway/amqp.Open
	/home/ec2-user/heka/build/heka/src/github.com/streadway/amqp/connection.go:214 +0x38e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 18 [runnable]:
github.com/streadway/amqp.(*Connection).heartbeater(0xc208052140, 0x2540be400, 0xc20805c000)
	/home/ec2-user/heka/build/heka/src/github.com/streadway/amqp/connection.go:483 +0x479
created by github.com/streadway/amqp.(*Connection).openTune
	/home/ec2-user/heka/build/heka/src/github.com/streadway/amqp/connection.go:653 +0x7c7

goroutine 9 [chan receive]:
github.com/mozilla-services/heka/plugins/amqp.func·006(0xc2080508a0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/amqp/types.go:153 +0x61
created by github.com/mozilla-services/heka/plugins/amqp.(*amqpConnectionHub).GetChannel
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/amqp/types.go:161 +0x527

goroutine 10 [select]:
github.com/mozilla-services/heka/plugins/elasticsearch.(*ElasticSearchOutput).Run(0xc20808eb60, 0x7f4953339b10, 0xc208060000, 0x7f495333b498, 0xc20803a820, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/elasticsearch/elasticsearch.go:238 +0xe46
github.com/mozilla-services/heka/pipeline.(*foRunner).Starter(0xc208060000, 0x7f495333b498, 0xc20803a820, 0xc2080d2420)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:882 +0x7dd
created by github.com/mozilla-services/heka/pipeline.(*foRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:771 +0x66c

goroutine 11 [chan receive]:
github.com/mozilla-services/heka/plugins.(*LogOutput).Run(0xfa1080, 0x7f4953339b10, 0xc208060160, 0x7f495333b498, 0xc20803a820, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/log_output.go:45 +0x1ca
github.com/mozilla-services/heka/pipeline.(*foRunner).Starter(0xc208060160, 0x7f495333b498, 0xc20803a820, 0xc2080d2420)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:882 +0x7dd
created by github.com/mozilla-services/heka/pipeline.(*foRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:771 +0x66c

goroutine 12 [select]:
github.com/mozilla-services/heka/plugins/file.(*FileOutput).receiver(0xc20805c3c0, 0x7f4953339b10, 0xc2080602c0, 0xc20805c1e0, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/file/file_output.go:236 +0x7ea
github.com/mozilla-services/heka/plugins/file.(*FileOutput).Run(0xc20805c3c0, 0x7f4953339b10, 0xc2080602c0, 0x7f495333b498, 0xc20803a820, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/file/file_output.go:210 +0x227
github.com/mozilla-services/heka/pipeline.(*foRunner).Starter(0xc2080602c0, 0x7f495333b498, 0xc20803a820, 0xc2080d2420)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:882 +0x7dd
created by github.com/mozilla-services/heka/pipeline.(*foRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:771 +0x66c

goroutine 13 [select]:
github.com/mozilla-services/heka/plugins/dasher.(*DashboardOutput).Run(0xc20808f490, 0x7f4953339b10, 0xc208060420, 0x7f495333b498, 0xc20803a820, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/dasher/dashboard_output.go:184 +0x1e66
github.com/mozilla-services/heka/pipeline.(*foRunner).Starter(0xc208060420, 0x7f495333b498, 0xc20803a820, 0xc2080d2420)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:882 +0x7dd
created by github.com/mozilla-services/heka/pipeline.(*foRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:771 +0x66c

goroutine 19 [chan receive]:
github.com/mozilla-services/heka/pipeline.func·019()
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:278 +0xf8
created by github.com/mozilla-services/heka/pipeline.(*MatchRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:315 +0x11c

goroutine 34 [chan receive]:
github.com/mozilla-services/heka/pipeline.func·019()
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:278 +0xf8
created by github.com/mozilla-services/heka/pipeline.(*MatchRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:315 +0x11c

goroutine 35 [select]:
github.com/mozilla-services/heka/plugins/file.(*FileOutput).committer(0xc20805c3c0, 0x7f4953339b10, 0xc2080602c0, 0xc20805c1e0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/file/file_output.go:307 +0xb7b
created by github.com/mozilla-services/heka/plugins/file.(*FileOutput).Run
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/file/file_output.go:209 +0x1f3

goroutine 36 [chan receive]:
github.com/mozilla-services/heka/pipeline.func·019()
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:278 +0xf8
created by github.com/mozilla-services/heka/pipeline.(*MatchRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:315 +0x11c

goroutine 50 [chan receive]:
github.com/mozilla-services/heka/pipeline.func·019()
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:278 +0xf8
created by github.com/mozilla-services/heka/pipeline.(*MatchRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:315 +0x11c

goroutine 51 [IO wait]:
net.(*pollDesc).Wait(0xc2081140d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081140d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208114070, 0x0, 0x7f4953333d30, 0xc20809a020)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208030048, 0x69b604, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208030048, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20805cde0, 0x7f495333b810, 0xc208030048, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20805cde0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1718 +0x154
github.com/mozilla-services/heka/plugins/dasher.defaultStarter(0xc20808f490, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/dasher/dashboard_output.go:299 +0x3e
created by github.com/mozilla-services/heka/plugins/dasher.(*DashboardOutput).Run
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/dasher/dashboard_output.go:170 +0xa6

goroutine 20 [sleep]:
github.com/mozilla-services/heka/pipeline.(*BufferedOutput).streamOutput(0xc208120160, 0x7f495333b908, 0xc20808eb60, 0xc20805c720, 0xc20805c120, 0xc20808e150)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/buffered_output.go:259 +0x66c
created by github.com/mozilla-services/heka/pipeline.(*BufferedOutput).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/buffered_output.go:185 +0xbd

goroutine 14 [chan receive]:
github.com/mozilla-services/heka/pipeline.(*DiagnosticTracker).Run(0xc208118d80)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/packet_tracking.go:136 +0x195
created by github.com/mozilla-services/heka/pipeline.Run
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/pipeline_runner.go:252 +0xdf4

goroutine 15 [chan receive]:
github.com/mozilla-services/heka/pipeline.(*DiagnosticTracker).Run(0xc208118030)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/packet_tracking.go:136 +0x195
created by github.com/mozilla-services/heka/pipeline.Run
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/pipeline_runner.go:253 +0xe11

goroutine 16 [select]:
github.com/mozilla-services/heka/pipeline.func·017()
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:120 +0xa63
created by github.com/mozilla-services/heka/pipeline.(*messageRouter).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:192 +0x93

goroutine 66 [chan receive]:
github.com/mozilla-services/heka/plugins/amqp.(*AMQPInput).Run(0xc2080962c0, 0x7f49533377b0, 0xc208074d80, 0x7f495333b498, 0xc20803a820, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/amqp/amqp_input.go:188 +0x29a
github.com/mozilla-services/heka/pipeline.(*iRunner).Starter(0xc208074d80, 0x7f495333b498, 0xc20803a820, 0xc20803a960)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:283 +0x180
created by github.com/mozilla-services/heka/pipeline.(*iRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:266 +0x606

goroutine 67 [IO wait]:
net.(*pollDesc).Wait(0xc208114060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208114060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208114000, 0x0, 0x7f4953333d30, 0xc20809a080)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20805e028, 0xc208100380, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20805e028, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc20811c060, 0x7f495333b7d8, 0xc20805e028, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
github.com/mozilla-services/heka/plugins/http.defaultStarter(0xc20811c000, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/http/http_listen_input.go:67 +0x3d0
github.com/mozilla-services/heka/plugins/http.(*HttpListenInput).Run(0xc20811c000, 0x7f49533377b0, 0xc208074fc0, 0x7f495333b498, 0xc20803a820, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/http/http_listen_input.go:173 +0xb0
github.com/mozilla-services/heka/pipeline.(*iRunner).Starter(0xc208074fc0, 0x7f495333b498, 0xc20803a820, 0xc20803a960)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:283 +0x180
created by github.com/mozilla-services/heka/pipeline.(*iRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:266 +0x606

goroutine 68 [select]:
github.com/mozilla-services/heka/plugins/logstreamer.(*LogstreamerInput).Run(0xc208120000, 0x7f49533377b0, 0xc208075b00, 0x7f495333b498, 0xc20803a820, 0x0, 0x0)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/plugins/logstreamer/logstreamer_input.go:210 +0xa4b
github.com/mozilla-services/heka/pipeline.(*iRunner).Starter(0xc208075b00, 0x7f495333b498, 0xc20803a820, 0xc20803a960)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:283 +0x180
created by github.com/mozilla-services/heka/pipeline.(*iRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:266 +0x606

goroutine 37 [chan receive]:
github.com/streadway/amqp.bufferDeliveries(0xc20805dec0, 0xc20805d560)
	/home/ec2-user/heka/build/heka/src/github.com/streadway/amqp/consumers.go:38 +0x88
created by github.com/streadway/amqp.(*consumers).add
	/home/ec2-user/heka/build/heka/src/github.com/streadway/amqp/consumers.go:74 +0xfb

goroutine 38 [chan receive]:
github.com/streadway/amqp.bufferDeliveries(0xc20805c840, 0xc20805c7e0)
	/home/ec2-user/heka/build/heka/src/github.com/streadway/amqp/consumers.go:38 +0x88
created by github.com/streadway/amqp.(*consumers).add
	/home/ec2-user/heka/build/heka/src/github.com/streadway/amqp/consumers.go:74 +0xfb

goroutine 70 [runnable]:
github.com/mozilla-services/heka/pipeline.(*iRunner).Starter(0xc2080fca20, 0x7f495333b498, 0xc20803a820, 0xc20803a960)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:270
created by github.com/mozilla-services/heka/pipeline.(*iRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:266 +0x606

goroutine 71 [runnable]:
github.com/mozilla-services/heka/pipeline.(*iRunner).Starter(0xc20809c6c0, 0x7f495333b498, 0xc20803a820, 0xc20803a960)
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:270
created by github.com/mozilla-services/heka/pipeline.(*iRunner).Start
	/home/ec2-user/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:266 +0x606

**Comment by rafrombrc** [comment]
Okay, #1454 fixed the panic, and #1480 causes the `deliver_incomplete_final` setting to apply to non-streaming, packet-based inputs, which provides a mechanism for capturing trailing records or records with no delimiter at all.
