### ISSUE TITLE
Panic when an output queue fills up and service is restarted

### ISSUE THREAD

**Issue by asenchi** [mozilla-services/heka#1507]
Hello!

I recently configured my ElasticSearchOutput with the new features in 0.9 around queue management. I'm running this for a configuration:

```
[logsearch-java-services]
type = "ElasticSearchOutput"
server = "http://elasticsearch-cluster:9200"
message_matcher = 'Logger =~ /java-service/'
encoder = "elasticsearch-java-services"
flush_interval = 50
queue_max_buffer_size = 5000000000
queue_full_action = 'drop'
```

Recently I had an ES cluster issue, that was causing some back pressure. This output reach it's max_buffer_size but never seemed to recover. I'm actually still working through why that is happening but I noticed something else when I tried to restart the heka service: https://gist.github.com/asenchi/6aa681946a9874838d40#file-heka-log

It seems as though there is a bug here? I wouldn't expect it to panic on the full buffer. Either way I wanted to report it for further discussion to perhaps fix an issue I may have introduced in my configuration.

**Comment by rafrombrc** [comment]
Re: not recovering from the queue being full... that issue was previously reported, should be fixed as of 0.9.2 release. Are you running 0.9.2? If not, can you upgrade and see whether the problem is resolved?

**Comment by asenchi** [comment]
Ah, I'm not. Sorry I must've missed that release.

**Comment by rafrombrc** [comment]
I've taken a look at the panic traceback and I'm not quite sure what's going on there. Is that something that happened when you were trying to shut down? The following line of code seems to be where the panic is happening:

```go
message.NewInt64Field(msg, "SentMessageCount", atomic.LoadInt64(&b.sentMessageCount), "count")
```

In order for the panic to happen either `msg`, `b`, or `b.sentMessageCount` would have to be nil. AFAICT `b.sentMessageCount` *can't* be nil, b/c it's not a pointer. If `msg` were nil, then I would have expected the panic to happen sooner in the calling code in `elasticsearch.go`. If `b` (the buffered output itself) were nil then there would have been big problems much sooner.

My guess is that things were wedged because of the no-recovery bug, you initiated a shutdown, and the shutdown caused either `msg` or `b` to become nil in a race condition with the ReportMsg method, generating the panic. That's just speculation, though.

**Comment by asenchi** [comment]
FYI, the panic was spewing into logs over and over again, not sure if that changes your speculation. I'll upgrade and see if I can reproduce the behavior to test.

**Comment by 4r9h** [comment]
Hi everyone,

After some code reading i think there's a possibility that ESOutput sets
outputbuffer to nil:
https://github.com/mozilla-services/heka/blob/dev/plugins/elasticsearch/elasticsearch.go#L228

NewBufferedOutput can return nil when it's impossible to create queue
folder or if creation of splitter fails. That could cause situation when
Pointer to buffedouputput would be nil.
Also, i think that QueueIsFull error is possible only when outputbuffer
tries to call queuerecord(), so that (probably) should be false everytime.

On Thu, Apr 30, 2015 at 11:22 PM, Curt Micol <notifications@github.com>
wrote:

> FYI, the panic was spewing into logs over and over again, not sure if that
> changes your speculation. I'll upgrade and see if I can reproduce the
> behavior to test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla-services/heka/issues/1507#issuecomment-97972437>
> .
>



-- 
jarek@reijutsu:~$ fortune
You have Egyptian flu: you're going to be a mummy.
jarek@reijutsu:~$ fortune
You now have Asian Flu.

**Comment by samos123** [comment]
I'm running heka 0.10 but seems I'm still hitting the issue. Any way to workaround this and fix a running environment?

Logs:

```
 broken pipe
2016/06/28 07:46:30 Plugin 'aggregator_tcpoutput' error: can't send record: writing to 192.168.10.2:5565: write tcp 192.168.10.2:5565:
 broken pipe
2016/06/28 08:29:03 Plugin 'influxdb_output' error: updating buffer cursor: can't parse queue cursor '': invalid checkpoint format
2016/06/28 08:29:05 http: panic serving 127.0.0.1:46271: send on closed channel
goroutine 274 [running]:
net/http.func·011()
        /usr/lib/go/src/net/http/server.go:1130 +0xbb
github.com/mozilla-services/heka/pipeline.func·009(0xc2082ccd00)
        /home/elemoine/src/go-workspace/src/github.com/elemoine/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:456 +0x4a
github.com/mozilla-services/heka/pipeline.(*iRunner).Deliver(0xc208043cc0, 0xc2082ccd00)
        /home/elemoine/src/go-workspace/src/github.com/elemoine/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:534 +0xc2
github.com/mozilla-services/heka/pipeline.(*sRunner).DeliverRecord(0xc20e427ad0, 0xc20c4a7000, 0xf8a, 0x1000, 0x0, 0x0)
        /home/elemoine/src/go-workspace/src/github.com/elemoine/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/splitter_runner.go:284 +0x337
github.com/mozilla-services/heka/pipeline.(*sRunner).SplitStreamNullSplitterToEOF(0xc20e427ad0, 0x7f5ced35d2d8, 0xc20e6ca900, 0x0, 0x0, 0x0, 0x0)
        /home/elemoine/src/go-workspace/src/github.com/elemoine/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/splitter_runner.go:410 +0x50a
github.com/mozilla-services/heka/plugins/http.(*HttpListenInput).RequestHandler(0xc20800d860, 0x7f5ced35d2a0, 0xc20da3c0a0, 0xc20d00a0d0)
        /home/elemoine/src/go-workspace/src/github.com/elemoine/heka/build/heka/src/github.com/mozilla-services/heka/plugins/http/http_listen_input.go:201 +0x43c
github.com/mozilla-services/heka/plugins/http.*HttpListenInput.RequestHandler·fm(0x7f5ced35d2a0, 0xc20da3c0a0, 0xc20d00a0d0)
        /home/elemoine/src/go-workspace/src/github.com/elemoine/heka/build/heka/src/github.com/mozilla-services/heka/plugins/http/http_listen_input.go:217 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2080b0b20, 0x7f5ced35d2a0, 0xc20da3c0a0, 0xc20d00a0d0)
        /usr/lib/go/src/net/http/server.go:1265 +0x41
github.com/mozilla-services/heka/plugins/http.func·007(0x7f5ced35d2a0, 0xc20da3c0a0, 0xc20d00a0d0)
:
```
