### ISSUE TITLE
heka panics when I create a long lpeg grammar in sanbox filter

### ISSUE THREAD

**Issue by liyichao** [mozilla-services/heka#1745]
My sandbox is:

```
local l = require 'lpeg'
l.locale(l)

function exact(pat, n)
   return -pat^(n + 1) * pat^n
end

local sep = l.space ^ 1
local levelname = l.Cg(l.S("DIWEC"), "level")
local time = l.Cg(exact(l.digit, 6) * sep *
                     exact(l.digit, 2) * ":" *
                     exact(l.digit, 2) * ":" *
                     exact(l.digit, 2), "time")
local module_line = l.alnum^1 * ":" * l.digit^1
local hostname_pid = module_line
local trace_id = l.Cg(exact(l.R("09", "af"), 16), "trace_id")
local span_id = l.Cg(exact(l.R("09", "af"), 16), "span_id")
local parent_id = l.Cg(exact(l.R("09", "af"), 16) + "None", "parent_id")
local sampled = l.Cg(l.P"True" + l.P"False", "sampled")
local prefix = l.P"[" * levelname * sep * time * sep * module_line * sep * hostname_pid * sep * trace_id * sep * span_id * sep * parent_id * sep * sampled * l.P"]"
local pattern = l.Ct(prefix)
function process_message()
   local m = read_message("Payload")
   rst = l.match(pattern, m)
   inject_payload("ttttt", "", rst)
   return 0
end

```

It panics when start:

```

hekad(18516,0xb0104000) malloc: *** error for object 0x5618d60: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff93dd8286 m=3
signal arrived during cgo execution

goroutine 7 [syscall, locked to thread]:
runtime.cgocall(0x4002920, 0xc820043b38, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/runtime/cgocall.go:120 +0x11b fp=0xc820043b08 sp=0xc820043ad8
github.com/mozilla-services/heka/sandbox/lua._Cfunc_process_message(0x55008f0, 0x0)
	github.com/mozilla-services/heka/sandbox/lua/_obj/_cgo_gotypes.go:160 +0x35 fp=0xc820043b38 sp=0xc820043b08
github.com/mozilla-services/heka/sandbox/lua.(*LuaSandbox).ProcessMessage(0xc820017e80, 0xc820081780, 0x4a7f740)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/sandbox/lua/lua_sandbox.go:755 +0x44 fp=0xc820043b50 sp=0xc820043b38
github.com/mozilla-services/heka/sandbox/plugins.(*SandboxFilter).Run(0xc8200ee820, 0x53a69d8, 0xc8200f04e0, 0x53a6bf8, 0xc82010a000, 0x0, 0x0)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/sandbox/plugins/sandbox_filter.go:259 +0x1094 fp=0xc820043e28 sp=0xc820043b50
github.com/mozilla-services/heka/pipeline.(*foRunner).OldStarter(0xc8200f04e0, 0x53a6bf8, 0xc82010a000, 0xc82010a090)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:1432 +0x804 fp=0xc820043f90 sp=0xc820043e28
runtime.goexit()
	/usr/local/Cellar/go/1.5/libexec/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820043f98 sp=0xc820043f90
created by github.com/mozilla-services/heka/pipeline.(*foRunner).Start
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:1019 +0xc16

goroutine 1 [chan receive]:
github.com/mozilla-services/heka/pipeline.Run(0xc82010a000)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/pipeline_runner.go:335 +0x14eb
main.main()
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/cmd/hekad/main.go:192 +0x12b9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/mozilla-services/heka/plugins.(*LogOutput).Run(0xc820121da0, 0x53a6b18, 0xc8200f0680, 0x53a6bf8, 0xc82010a000, 0x0, 0x0)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/plugins/log_output.go:50 +0x1b3
github.com/mozilla-services/heka/pipeline.(*foRunner).OldStarter(0xc8200f0680, 0x53a6bf8, 0xc82010a000, 0xc820121fa0)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:1435 +0x955
created by github.com/mozilla-services/heka/pipeline.(*foRunner).Start
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:1019 +0xc16

goroutine 10 [chan receive]:
github.com/mozilla-services/heka/pipeline.(*MatchRunner).run(0xc820081580, 0x3e8)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:307 +0xe7
created by github.com/mozilla-services/heka/pipeline.(*MatchRunner).Start
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:360 +0x3f

goroutine 11 [chan receive]:
github.com/mozilla-services/heka/pipeline.(*MatchRunner).run(0xc820081500, 0x3e8)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:307 +0xe7
created by github.com/mozilla-services/heka/pipeline.(*MatchRunner).Start
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:360 +0x3f

goroutine 12 [chan receive]:
github.com/mozilla-services/heka/pipeline.(*DiagnosticTracker).Run(0xc8200f3470)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/packet_tracking.go:136 +0x1ac
created by github.com/mozilla-services/heka/pipeline.Run
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/pipeline_runner.go:312 +0xdc4

goroutine 13 [chan receive]:
github.com/mozilla-services/heka/pipeline.(*DiagnosticTracker).Run(0xc8200f34a0)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/packet_tracking.go:136 +0x1ac
created by github.com/mozilla-services/heka/pipeline.Run
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/pipeline_runner.go:313 +0xde9

goroutine 14 [runnable]:
runtime.Gosched()
	/usr/local/Cellar/go/1.5/libexec/src/runtime/proc.go:166 +0x14
github.com/mozilla-services/heka/pipeline.(*messageRouter).Start.func1(0xc8200e3960)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:135 +0x37
created by github.com/mozilla-services/heka/pipeline.(*messageRouter).Start
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/router.go:208 +0x39

goroutine 15 [IO wait]:
net.runtime_pollWait(0x53a6488, 0x72, 0xc8200101e0)
	/usr/local/Cellar/go/1.5/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820122290, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820122290, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820122230, 0xc820124000, 0x1000, 0x1000, 0x0, 0x53a0050, 0xc8200101e0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820032128, 0xc820124000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc82001d380)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82001d380, 0xc82001670a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:328 +0x21a
github.com/garyburd/redigo/redis.(*conn).readLine(0xc8200ee780, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/garyburd/redigo/redis/conn.go:338 +0x5a
github.com/garyburd/redigo/redis.(*conn).readReply(0xc8200ee780, 0x0, 0x0, 0x0, 0x0)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/garyburd/redigo/redis/conn.go:411 +0x57
github.com/garyburd/redigo/redis.(*conn).Receive(0xc8200ee780, 0x0, 0x0, 0x0, 0x0)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/garyburd/redigo/redis/conn.go:494 +0x162
github.com/garyburd/redigo/redis.PubSubConn.Receive(0x53a6598, 0xc8200ee780, 0x0, 0x0)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/garyburd/redigo/redis/pubsub.go:106 +0x5e
git.in.zhihu.com/lyc/heka-plugins.(*RedisPubSubInput).Run(0xc8200fdb20, 0x53a6618, 0xc820126000, 0x53a6bf8, 0xc82010a000, 0x0, 0x0)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/git.in.zhihu.com/lyc/heka-plugins/redis_pubsub_input.go:54 +0x240
github.com/mozilla-services/heka/pipeline.(*iRunner).Starter(0xc820126000, 0x53a6bf8, 0xc82010a000, 0xc82010a18c)
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:319 +0x1bb
created by github.com/mozilla-services/heka/pipeline.(*iRunner).Start
	/Users/liyichao/Projects/monitoring/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:299 +0x88d

goroutine 16 [select, locked to thread]:
runtime.gopark(0x486cc50, 0xc82002c728, 0x4739520, 0x6, 0x4034118, 0x2)
	/usr/local/Cellar/go/1.5/libexec/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002c728, 0x0, 0x18)
	/usr/local/Cellar/go/1.5/libexec/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002c728)
	/usr/local/Cellar/go/1.5/libexec/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.5/libexec/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
	/usr/local/Cellar/go/1.5/libexec/src/runtime/asm_amd64.s:1696 +0x1

rax    0x0
rbx    0x6
rcx    0xb0103758
rdx    0x0
rdi    0xb03
rsi    0x6
rbp    0xb0103780
rsp    0xb0103758
r8     0x1
r9     0x0
r10    0x8000000
r11    0x206
r12    0xffffffffffffffdb
r13    0x1
r14    0xb0104000
r15    0x0
rip    0x7fff93dd8286
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

**Comment by trink** [comment]
I cannot reproduce this on the dev branch go 1.4.1. Also the use of inject_payload is incorrect (it does not accept a table). I will fix the typo in the error message.

bad argument #3 to 'inject_payload' (unsuported type)

**Comment by liyichao** [comment]
I use go 1.5. It panics before process_message is called, near `local prefix`. It is ok in v0.9.2.

**Comment by rafrombrc** [comment]
I recommend using Go 1.4.3... I see very poor multi-core performance and sometimes strange panics on 1.5 so far.
