### ISSUE TITLE
what does version of heka will support version 1.6 of golang?

### ISSUE THREAD

**Issue by affinity226** [mozilla-services/heka#1979]
now i use 0.10.0 version of heka.

it doesn't run on go 1.6.

i guess some part of sandbox plugin loading or running has issues.

**Comment by robison** [comment]
As of right now, this is not on the roadmap.

**Comment by michaelgibson** [comment]
Building heka with go 1.6 results in the binary crashing on startup.

panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 21 [running]:
panic(0xb28c80, 0xc820116ec0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/mozilla-services/heka/sandbox/lua._cgoCheckPointer0(0xa00de0, 0xc820012a40, 0x0, 0x0, 0x0, 0x7f2718000900)
	github.com/mozilla-services/heka/sandbox/lua/_obj/_cgo_gotypes.go:65 +0x4d
github.com/mozilla-services/heka/sandbox/lua.CreateLuaSandbox(0xc820133100, 0x0, 0x0, 0x0, 0x0)
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/sandbox/lua/lua_sandbox.go:697 +0x92a
github.com/mozilla-services/heka/sandbox/plugins.(*SandboxDecoder).SetDecoderRunner(0xc8200984d0, 0x7f272a62b808, 0xc82011f8c0)
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/sandbox/plugins/sandbox_decoder.go:152 +0x120
github.com/mozilla-services/heka/pipeline.(*dRunner).Start(0xc82011f8c0, 0x7f272a5e9800, 0xc820154000, 0xc8201540a0)
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:624 +0x160
github.com/mozilla-services/heka/pipeline.(*PipelineConfig).DecoderRunner(0xc820154000, 0xc8201762f0, 0xe, 0xc8201382a0, 0x17, 0x7f272a62b808, 0xc82011f8c0, 0x1)
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/config.go:324 +0x358
github.com/mozilla-services/heka/pipeline.(*iRunner).getDeliverFunc(0xc820127cc0, 0xc820116909, 0x1, 0xc820180000, 0x0, 0x0, 0x0, 0x0)
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:452 +0x545
github.com/mozilla-services/heka/pipeline.(*iRunner).NewDeliverer(0xc820127cc0, 0xc820116909, 0x1, 0x0, 0x0)
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:514 +0x51
github.com/mozilla-services/heka/plugins/logstreamer.(*LogstreamerInput).startLogstreamInput(0xc820098840, 0xc82008db00, 0x1, 0x7f272a62fbe8, 0xc820127cc0, 0x7f272a5e9800, 0xc820154000)
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/plugins/logstreamer/logstreamer_input.go:196 +0x8e
github.com/mozilla-services/heka/plugins/logstreamer.(*LogstreamerInput).Run(0xc820098840, 0x7f272a62fbe8, 0xc820127cc0, 0x7f272a5e9800, 0xc820154000, 0x0, 0x0)
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/plugins/logstreamer/logstreamer_input.go:216 +0x132
github.com/mozilla-services/heka/pipeline.(*iRunner).Starter(0xc820127cc0, 0x7f272a5e9800, 0xc820154000, 0xc82015418c)
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:325 +0x1b7
created by github.com/mozilla-services/heka/pipeline.(*iRunner).Start
	/data/github/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:305 +0x88d

This is due to a new check in the runtime : https://golang.org/doc/go1.6#cgo

This should probably be addressed in the code somewhere but there is a workaround.
Run:
export GODEBUG=cgocheck=0
Before building to disable the check.

**Comment by michaelgibson** [comment]
There is a workaround for building on 1.6.
See: https://github.com/mozilla-services/heka/issues/1881#issuecomment-237322744
Please close as duplicate.
